name: Get Events

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout hackertracker-export
        uses: actions/checkout@v4
        with:
          repository: cak/hackertracker-export
          path: hackertracker-export

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch events
        run: |
          npm install --prefix hackertracker-export
          npm run export --prefix hackertracker-export
          cp -r hackertracker-export/out/ht ./docs/

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/ht
          git commit -m "update ht events" || true
          git push
